"$schema" = 'https://starship.rs/config-schema.json'

[git_branch]
symbol = "󰘬 "

[git_commit]
tag_symbol = " 󰓼 "

[package]
symbol = "󰏗 "

[aws]
disabled = true
symbol = "󰅣 "
[aws.region_aliases]
us-east-1 = "use1"
us-east-2 = "use2"
us-west-1 = "usw1"
us-west-2 = "usw2"
